import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from '@/app/StoreProvider'
import SideNav from "./components/basic/SideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "TODO App",
  description: "Generated by todo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <StoreProvider>
          <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <SideNav />
            <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
